[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook-source = '''
  let g:go_fmt_autosave = 1
  let g:go_metalinter_excludes = ['.*\.pb\.go', '.*_mock\.go']
  let g:go_metalinter_deadline = '1m'
  let g:go_term_enabled = 1
  let g:go_gocode_autobuild = 0
  let g:go_gocode_unimported_packages = 1
  let g:go_highlight_array_whitespace_error = 1
  let g:go_highlight_chan_whitespace_error = 1
  let g:go_highlight_extra_types = 1
  let g:go_highlight_space_tab_error = 1
  let g:go_highlight_trailing_whitespace_error = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_functions = 1
  let g:go_highlight_function_arguments = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_types = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_build_constraints = 1
  let g:go_highlight_generate_tags = 1
  let g:go_highlight_string_spellcheck = 1
  let g:go_highlight_format_strings = 1
  let g:go_highlight_variable_declarations = 1
  let g:go_highlight_variable_assignments = 1
'''

[[plugins]]
# deoplete
repo = 'Shougo/deoplete.nvim'
hook_post_source = '''
    let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-3.8/lib/libclang-3.8.so.1'
    let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
    let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
# deoplete-clang
repo = 'zchee/deoplete-clang'

[[plugins]]
repo = 'zchee/deoplete-go'
build =  'make'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-pathogen'
