[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'nsf/gocode'
rtp = 'vim'
